using System.IO; // For Path.Combine
using Sharpmake; // Contains the entire Sharpmake object library.

// Represents the project that will be generated by Sharpmake and that contains
// the sample C++ code.

[module: Sharpmake.Include("globals.cs")]
[module: Sharpmake.Include("KNRGraphics.make.cs")]
[module: Sharpmake.Include("KNRBaseProject.make.cs")]
[module: Sharpmake.Include("KNRShaders.make.cs")]
[module: Sharpmake.Include("KNRShaderCompiler.make.cs")]

[Generate]
public class KNRSln : Solution
{    
    public KNRSln()
    {
        Name = "KNR";
        AddTargets(new Target(
                Platform.win32 | Platform.win64,
                DevEnv.vs2019,
                Optimization.Debug | Optimization.Release
        ));
    }

    [Configure]
    public void Configure(Configuration conf, Target target)
    {
        conf.SolutionFileName = "[solution.Name]";
        conf.SolutionPath = Globals.ProjectRoot;
        conf.AddProject<SandboxProject>(target);
        conf.AddProject<KNRGraphics>(target);
        conf.AddProject<KNRShaders>(target);
        conf.AddProject<KNRShaderCompiler>(target);
    }
}

[Generate]
public class SandboxProject : KNRExeBase
{
    public string[] GetDefinesByOptimization(Target target)
    {
        switch (target.Optimization)
        {
        case Optimization.Debug:
        case Optimization.Release:
            return new[]{
                "_KNR_",
            };
        }

        return null;
    }

    public SandboxProject()
        :base("Sandbox")
    {
        SourceRootPath = Globals.CoreDir;
    }
    [Configure]
    public void ConfigureAll(Configuration conf, Target target)
    {
        SetUpVisualStudioOptions(conf, target);

        conf.ProjectFileName = "[project.Name]";
        conf.ProjectPath = Globals.BuildDir;

        conf.AddPrivateDependency<KNRGraphics>(target);
        conf.AddPrivateDependency<KNRShaders>(target);

        conf.Defines.AddRange(GetDefinesByOptimization(target));

        // if not set, no precompile option will be used.
        conf.CustomProperties.Add("CustomOptimizationProperty", $"Custom-{target.Optimization}");
    }
}


public static class Main
{
    [Sharpmake.Main]
    public static void SharpmakeMain(Sharpmake.Arguments arguments)
    {
        KitsRootPaths.SetUseKitsRootForDevEnv(DevEnv.vs2019, KitsRootEnum.KitsRoot10, Options.Vc.General.WindowsTargetPlatformVersion.v10_0_19041_0);
       
        //Solutions to generate
        arguments.Generate<KNRSln>();
    }
}